<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Broiler.Mail.Core/Broiler.Mail.Core.csproj" />
    <PackageReference Include="Broiler.UI.Button.Standard" />
    <PackageReference Include="Broiler.UI.ComboBox.Standard" />
    <PackageReference Include="Broiler.UI.Edit.Standard" />
    <PackageReference Include="Broiler.UI.Label.Standard" />
    <PackageReference Include="Broiler.UI.ListView.Standard" />
    <PackageReference Include="Broiler.UI.Panel.Standard" />
    <PackageReference Include="Broiler.UI.ScrollView.Standard" />
    <PackageReference Include="Broiler.UI.TabView.Standard" />
    <PackageReference Include="Broiler.UI.Window.Standard" />
  </ItemGroup>
</Project>
