<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PublishAot>true</PublishAot>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <JsonSerializerIsReflectionEnabledByDefault>false</JsonSerializerIsReflectionEnabledByDefault>
  </PropertyGroup>
  <ItemGroup>
    <IlcArg Include="--substitution:$(MSBuildThisFileDirectory)NativeAot.Substitutions.xml" Condition="'$(PublishAot)' == 'true'" />
    <PackageReference Include="Broiler.HTML.Core" />
    <PackageReference Include="Broiler.HTML.Image" />
    <PackageReference Include="Broiler.HTML.Image.Compat" />
    <PackageReference Include="Broiler.Media.Image.Managed" />
    <InternalsVisibleTo Include="Broiler.Mail.Windows.Tests" />
    <ProjectReference Include="../Broiler.Mail.Application/Broiler.Mail.Application.csproj" />
    <ProjectReference Include="../Broiler.Mail.Infrastructure/Broiler.Mail.Infrastructure.csproj" />
    <ProjectReference Include="../../../Broiler.Hosting/src/Broiler.Hosting.Windows/Broiler.Hosting.Windows.csproj" />
    <PackageReference Include="Broiler.Graphics.Windows" />
    <PackageReference Include="Broiler.Native.Windows" />
  </ItemGroup>
</Project>
